app-vac-bootcamp24-ecom/src/apps/vacunas/urls.py
from tkinter.font import names

from django.urls import path
from . import views

app_name = "vacunas"

urlpatterns = [
    # lista vacunas
    path('lista/', views.Listar.as_view(), name="lista"), # tarea: hacer busqueda
    # crear vacuna  -> tarea
    # editar vacuna
    path('vacuna/<int:pk>/editar', views.VacunaUpdate.as_view(), name='editar'),
    # detalle vacuna
    path('vacuna/<int:pk>/', views.VacunaDetail.as_view(), name='detalle'),
    # eliminar vacuna
    path('vacuna/<int:pk>/eliminar',views.VacunaDeleteView.as_view(), name='eliminar')

]

app-vac-bootcamp24-ecom/src/config/urls.py
from django.contrib import admin
from django.contrib.auth import views as views_django
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('inicio/', views.mi_pagina_inicio, name="inicio"),
    path('', views.mi_pagina_inicio, name="inicio"),

    path('base', views.BaseTemplateView.as_view(), name='base'),

    # path('login/', views.login, name="login"),
    # path('login/', views_django.LoginView.as_view(), name="login"),
    path('login/', views_django.LoginView.as_view(template_name="login_new.html"), name="login"),
    path('logout/', views_django.logout_then_login, name="logout"),
    
    # path('usuarios/lista/', views.lista_usuarios, name="lista_de_usuarios"),
    path('usuarios/', include("apps.usuarios.urls")),
    path('pacientes/', include("apps.pacientes.urls")),
    path('vacunas/', include("apps.vacunas.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app-vac-bootcamp24-ecom/src/apps/vacunas/models.py
from django.db import models

#  vacuna:
# -  nombre: Aztrazeneca
# - codigo    683
# - nombre tecnico * ....
# - cantidad de dosis 3


# dosis:
# - es de una vacuna -> referencia a la vacuna -> ForeignKey
# - nombre
# - orden

class Vacuna(models.Model):
    codigo = models.IntegerField()
    nombre = models.CharField(max_length=500)
    ca_dosis = models.IntegerField(default=1)

    class Meta:
        db_table = 'vacunas'
        verbose_name = u'vacuna'
        verbose_name_plural = u'vacunas'

    def __str__(self):
        return self.nombre


class Dosis(models.Model):
    vacuna = models.ForeignKey(Vacuna, related_name='dosis_de_vacuna', on_delete=models.CASCADE, null=True)  # quitar , null=True
    orden = models.IntegerField()
    nombre = models.CharField(max_length=500)

    class Meta:
        db_table = 'dosis'
        verbose_name = u'dosis'
        verbose_name_plural = u'dosis'

    def __str__(self):
        return self.nombre

app-vac-bootcamp24-ecom/src/apps/vacunas/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic import UpdateView, DetailView
from django.views.generic.edit import DeleteView
from .models import Vacuna, Dosis


class Listar(ListView):
    template_name = 'vacunas/lista.html'
    model = Vacuna
    context_object_name = "vacunas"
    paginate_by = 20

    def get_context_data(self, **kwargs):
        ctx = super(Listar, self).get_context_data(**kwargs)
        ctx["titulo"] = "LISTA DE VACUNAS"
        return ctx

class VacunaUpdate(UpdateView):
    model = Vacuna
    fields = ['codigo', 'nombre', 'ca_dosis']
    template_name = 'vacunas/editar.html'
    success_url = reverse_lazy('vacunas:lista')  # Redirigir a la lista de vacunas después de la edición

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Editar Vacuna'
        return context

class VacunaDetail(DetailView):
    model = Vacuna
    template_name = 'vacunas/detalle.html'
    context_object_name = 'vacuna'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dosis'] = Dosis.objects.filter(vacuna=self.object)
        return context

class VacunaDeleteView(DeleteView):
    model = Vacuna
    template_name = 'vacunas/confirmar_eliminacion.html'
    success_url = reverse_lazy('vacunas:lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dosis'] = Dosis.objects.filter(vacuna=self.object)
        return context

app-vac-bootcamp24-ecom/src/templates/vacunas/confirmar_eliminacion.html
{% extends 'base/base.html' %}



{% block contenido %}
 <h2>¿Estás seguro de que deseas eliminar la vacuna "{{ object }}"?</h2>
  <p>Esta acción también eliminará las dosis asociadas:</p>
  <ul>
    {% for dosis in dosis %}
      <li>{{ dosis.nombre }} (Orden: {{ dosis.orden }})</li>
    {% endfor %}
  </ul>

  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirmar eliminación</button>
    <a href="{% url 'vacunas:lista' %}">Cancelar</a>
  </form>
{% endblock contenido %}

app-vac-bootcamp24-ecom/src/templates/vacunas/detalle.html
{% extends 'base/base.html' %}

{% block contenido %}
    <h1>{{ vacuna.nombre }}</h1>
    <p>Código: {{ vacuna.codigo }}</p>
    <p>Dosis requeridas: {{ vacuna.ca_dosis }}</p>

    <h2>Dosis asociadas</h2>
    <ul>
        {% for dosis in dosis %}
            <li>{{ dosis.nombre }} (Orden: {{ dosis.orden }})</li>
        {% empty %}
            <li>No hay dosis asociadas para esta vacuna.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'vacunas:lista' %}">Volver a la lista de vacunas</a>

{% endblock contenido %}

app-vac-bootcamp24-ecom/src/templates/vacunas/editar.html
{% extends 'base/base.html' %}

{% block contenido %}
    <h1>{{ titulo }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
    <a href="{% url 'vacunas:lista' %}">Volver a la lista</a>
{% endblock contenido %}

app-vac-bootcamp24-ecom/src/templates/vacunas/lista.html
{% extends "base/base.html" %}

{% block block_title %}Vacunas{% endblock block_title %}


{% block contenido %}
	<div class="row">
		<div class="col-xl-12">
			<div class="card">
		        <div class="card-header">
		            <h5><i class="fas fa-vial"></i> {{titulo}}</h5>
		        </div>
		        <div class="card-block table-border-style">
		        	<div class="row">
						<div class="col-xl-12">
				        	<div class="btn-group right">
				        		<!--
								<a href=""><button type="button" class="btn btn-primary" title="" data-toggle="tooltip" data-original-title="Nueva Metadata"><i class="fas fa-plus"></i> Nuevo Centro de Vacunación</button></a>
								-->
							</div>
						</div>
					</div>
					<br>
		        	<div class="row">
						<div class="col-xl-12">
				      		<form method="GET">
				          		<div class="input-group">
				            		<input id="search" type="text" class="form-control" name="search" value="{{search}}" placeholder="Búsqueda por nombre de Usuarios" value="{{search}}">
				            		<span class="input-group-btn">
                                        <button type="submit" class="btn btn-primary m-0"><i class="fas fa-search prefix"></i> Buscar</button>
                                    </span>
				          		</div>
				      		</form>
					  	</div>
					</div>
					<br>
					<div class="table-responsive">
			            <table class="table table-columned">
							<thead>
								<tr>
									<th>Código</th>
									<th>Nombre</th>
									<th>Cantidad de dosis</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								{% for vacuna in vacunas %}
									<tr id="rowTurno_{{turno.id}}">
										<th>{{vacuna.codigo}}</th>
										<td>{{vacuna.nombre|default:'-'}}</td>
										<td>{{vacuna.ca_dosis}}</td>
									</tr>
								{% empty %}
									<tr>
										<td>No se encontraron resultados</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>

						{% include "includes/paginacion.html" %}


				</div>
			</div>
		</div>
	</div>
{% endblock contenido %}

app-vac-bootcamp24-ecom/src/templates/vacunas/lista_new.html
{% extends "base/base_nuevo.html" %}

{% block block_title %}Vacunas{% endblock block_title %}

    {% block css_extras %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    {% endblock css_extras %}

{% block content %}
    <main class="app-main"> <!--begin::App Content Header-->
        <div class="app-content-header"> <!--begin::Container-->
            <div class="container-fluid"> <!--begin::Row-->
                <div class="row">
                    <div class="col-sm-6">
                        <h3 class="mb-0">{{titulo}}</h3>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-end">
                            <li class="breadcrumb-item"><a href="{% url 'inicio' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">
                                {{titulo}}
                            </li>
                        </ol>
                    </div>
                </div> <!--end::Row-->
            </div> <!--end::Container-->
        </div> <!--end::App Content Header--> <!--begin::App Content-->
        <div class="app-content"> <!--begin::Container-->

			<div class="container-fluid"> <!--begin::Row-->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card mb-6">
                                <div class="card-header">
                                    <h3 class="card-title">Usuarios Registrados</h3>
                                </div> <!-- /.card-header -->
                                <div class="card-body">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th style="width: 20px">Código</th>
                                                <th>Nombre</th>
                                                <th style="width: 10px">Cantidad de dosis</th>
                                                <th style="width: 150px">Opciones</th>
                                            </tr>
                                        </thead>
                                        <tbody>
										{% for vacuna in vacunas %}
                                            <tr class="align-middle" id="rowTurno_{{turno.id}}">
                                                <td>{{vacuna.codigo}}</td>
                                                <td>{{vacuna.nombre|default:'-'}}</td>
                                                <td>{{vacuna.ca_dosis}} </td>
                                                <td>
													<a href="{% url 'vacunas:detalle' vacuna.id %}" class="btn btn-sm btn-info" title="Detalle">
														<i class="fas fa-eye"></i>
													</a>
													<a href="{% url 'vacunas:editar' vacuna.id %}" class="btn btn-sm btn-warning" title="Editar">
														<i class="fas fa-edit"></i>
													</a>
													<a href="{% url 'vacunas:eliminar' vacuna.id %}" class="btn btn-sm btn-danger" title="Eliminar">
														<i class="fas fa-trash-alt"></i>
													</a>
												</td>
                                            </tr>
										{% empty %}
											<tr>
												<td>No se encontraron resultados</td>
											</tr>
										{% endfor %}
                                        </tbody>
                                    </table>
                                </div> <!-- /.card-body -->
                                {% include "includes/paginacion.html" %}
                            </div> <!-- /.card -->

                        </div> <!-- /.col -->

                    </div> <!--end::Row-->
                </div> <!--end::Container-->

        </div> <!--end::App Content-->
    </main> <!--end::App Main-->
{% endblock content %}