app-vac-bootcamp24-ecom/src/apps/pacientes/urls.py
from django.urls import path

from . import views

app_name = "pacientes"

urlpatterns = [
    path('lista/', views.Lista.as_view(), name="lista"),
    # path('lista/', views.lista, name="lista"),
    # path('nuevo/', views.nuevo, name="nuevo"),
    path('nuevo/', views.Nuevo.as_view(), name="nuevo"),
]

app-vac-bootcamp24-ecom/src/apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = "usuarios"

urlpatterns = [
    path('lista/', views.lista_usuarios, name="lista"),
    path('nuevo/', views.nuevo, name="nuevo"),
]

app-vac-bootcamp24-ecom/src/apps/vacunas/urls.py
from tkinter.font import names

from django.urls import path
from . import views

app_name = "vacunas"

urlpatterns = [
    # lista vacunas
    path('lista/', views.Listar.as_view(), name="lista"), # tarea: hacer busqueda
    # crear vacuna  -> tarea
    # editar vacuna
    path('vacuna/<int:pk>/editar', views.VacunaUpdate.as_view(), name='editar'),
    # detalle vacuna
    path('vacuna/<int:pk>/', views.VacunaDetail.as_view(), name='detalle'),
    # eliminar vacuna
    path('vacuna/<int:pk>/eliminar',views.VacunaDeleteView.as_view(), name='eliminar')

]

app-vac-bootcamp24-ecom/src/config/urls.py
from django.contrib import admin
from django.contrib.auth import views as views_django
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('inicio/', views.mi_pagina_inicio, name="inicio"),
    path('', views.mi_pagina_inicio, name="inicio"),

    path('base', views.BaseTemplateView.as_view(), name='base'),

    # path('login/', views.login, name="login"),
    # path('login/', views_django.LoginView.as_view(), name="login"),
    path('login/', views_django.LoginView.as_view(template_name="login_new.html"), name="login"),
    path('logout/', views_django.logout_then_login, name="logout"),
    
    # path('usuarios/lista/', views.lista_usuarios, name="lista_de_usuarios"),
    path('usuarios/', include("apps.usuarios.urls")),
    path('pacientes/', include("apps.pacientes.urls")),
    path('vacunas/', include("apps.vacunas.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app-vac-bootcamp24-ecom/src/templates/base/barra_navegacion.html
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
    <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu"
        aria-labelledby="sidebarMenuLabel">
        <div class="offcanvas-header">
            <a href="{% url 'inicio' %}"><h5 class="offcanvas-title" id="sidebarMenuLabel">AppVac</h5></a>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas"
                data-bs-target="#sidebarMenu" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'usuarios:lista' %}">
                        <svg class="bi">
                            <use xlink:href="#people"></use>
                        </svg>
                        Lista de usuarios
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'pacientes:lista' %}">
                        <svg class="bi">
                            <use xlink:href="#graph-up"></use>
                        </svg>
                        Lista de pacientes
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'vacunas:lista' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag-heart" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0M14 14V5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1M8 7.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132"/>
                        </svg>
                        Lista de vacunas
                    </a>
                </li>
            </ul>

            <hr class="my-3">

            <ul class="nav flex-column mb-auto">

                {% if user.is_authenticated %}
                    <form action="{% url 'logout' %}" method="POST">{% csrf_token %}

                
                        <li class="nav-item">
                            <button class="nav-link d-flex align-items-center gap-2" type="submit">
                                <svg class="bi">
                                    <use xlink:href="#door-closed"></use>
                                </svg>
                                Salir
                            </button>
                        </li>
                    </form>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

app-vac-bootcamp24-ecom/src/templates/base/base_nuevo.html
{% load static %}
<!DOCTYPE html>
<html lang="es"> <!--begin::Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>
        {% block title_block %}
                Inicio
        {% endblock title_block %}
        | App Vac
    </title><!--begin::Primary Meta Tags-->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/source-sans-3@5.0.12/index.css" integrity="sha256-tXJfXfp6Ewt1ilPzLDtQnJV4hclT9XuaZUKyUvmyr+Q=" crossorigin="anonymous"><!--end::Fonts--><!--begin::Third Party Plugin(OverlayScrollbars)-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/overlayscrollbars@2.3.0/styles/overlayscrollbars.min.css" integrity="sha256-dSokZseQNT08wYEWiz5iLI8QPlKxG+TswNRD8k35cpg=" crossorigin="anonymous"><!--end::Third Party Plugin(OverlayScrollbars)--><!--begin::Third Party Plugin(Bootstrap Icons)-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.min.css" integrity="sha256-Qsx5lrStHZyR9REqhUF8iQt73X06c8LGIUPzpOhwRrI=" crossorigin="anonymous"><!--end::Third Party Plugin(Bootstrap Icons)--><!--begin::Required Plugin(AdminLTE)-->

    <link href="{% static 'css/adminlte.css' %}" rel="stylesheet" type="text/css" />

    {% block css_extras %}
    {% endblock css_extras %}

</head> <!--end::Head--> <!--begin::Body-->

<body class="layout-fixed sidebar-expand-lg bg-body-tertiary"> <!--begin::App Wrapper-->

    <div class="app-wrapper"> <!--begin::Header-->


  		{% include 'base/header.html' %}

        {% include 'base/left-side-menu.html' %}

        {% block content %}

        {% endblock content %}
        <!--begin::App Main-->

        {% include 'base/footer.html' %}




    </div> <!--end::App Wrapper--> <!--begin::Script--> <!--begin::Third Party Plugin(OverlayScrollbars)-->

	<script src="https://cdn.jsdelivr.net/npm/overlayscrollbars@2.3.0/browser/overlayscrollbars.browser.es6.min.js" integrity="sha256-H2VM7BKda+v2Z4+DRy69uknwxjyDRhszjXFhsL4gD3w=" crossorigin="anonymous"></script> <!--end::Third Party Plugin(OverlayScrollbars)--><!--begin::Required Plugin(popperjs for Bootstrap 5)-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha256-whL0tQWoY1Ku1iskqPFvmZ+CHsvmRWx/PIoEvIeWh4I=" crossorigin="anonymous"></script> <!--end::Required Plugin(popperjs for Bootstrap 5)--><!--begin::Required Plugin(Bootstrap 5)-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha256-YMa+wAM6QkVyz999odX7lPRxkoYAan8suedu4k2Zur8=" crossorigin="anonymous"></script> <!--end::Required Plugin(Bootstrap 5)--><!--begin::Required Plugin(AdminLTE)-->

    <script src="{% static 'js/adminlte.js' %}"></script>


    {% block js_extras %}
    {% endblock js_extras %}

</body><!--end::Body-->

</html>

app-vac-bootcamp24-ecom/src/templates/base/footer.html
<!--begin::Footer-->
<footer class="app-footer"> <!--begin::To the end-->
    <div class="float-end d-none d-sm-inline"></div> <!--end::To the end--> <!--begin::Copyright--> <strong>
        Curso Python &copy; 2024&nbsp;
        <a href="https://ecom.com.ar" class="text-decoration-none">Ecom Chaco</a>.
    </strong>
    <!--end::Copyright-->
</footer> <!--end::Footer-->

app-vac-bootcamp24-ecom/src/templates/base/header.html
{% load static %}

<nav class="app-header navbar navbar-expand bg-body"> <!--begin::Container-->
    <div class="container-fluid"> <!--begin::Start Navbar Links-->
        <ul class="navbar-nav">
            <li class="nav-item"> <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button"> <i class="bi bi-list"></i> </a> </li>

        </ul> <!--end::Start Navbar Links--> <!--begin::End Navbar Links-->

        <ul class="navbar-nav ms-auto"> <!--begin::Navbar Search-->

            <li class="nav-item dropdown user-menu"> <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"> <img src="{% static 'assets/img/user2-160x160.jpg' %}" class="user-image rounded-circle shadow" alt="User Image"> <span class="d-none d-md-inline">
                    {% if user.is_authenticated %}
                        {{user.username}}
                    {% else %}
                        <p><a href="{% url 'login' %}">SIN AUTENTICAR</a></p>
                    {% endif %}
            </span> </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-end"> <!--begin::User Image-->
                    <li class="user-header text-bg-primary"> <img src="{% static 'assets/img/user2-160x160.jpg' %}" class="rounded-circle shadow" alt="User Image">
                        <p>
                            {% if user.is_authenticated %}
                                <h3>{{user.get_full_name}}</h3>
                            {% else %}
                                <p><a href="{% url 'login' %}">SIN AUTENTICAR</a></p>
                            {% endif %}

                            <small>{Rol}</small>
                        </p>
                    </li> <!--end::User Image--> <!--begin::Menu Body-->
                    {% if user.is_superuser %}
                        <li class="user-body"> <!--begin::Row-->
                            <div class="row">
                                <div class="col-4 text-center"> <a href="{% url 'admin:index' %}">Admin Django</a> </div>

                            </div> <!--end::Row-->
                        </li> <!--end::Menu Body-->
                    {% endif %}
                    <!--begin::Menu Footer-->
                    <li class="user-footer"> <a href="#" class="btn btn-default btn-flat">Profile</a> <a href="{% url 'logout' %}" class="btn btn-default btn-flat float-end">Log out</a> </li> <!--end::Menu Footer-->
                </ul>
            </li> <!--end::User Menu Dropdown-->
        </ul> <!--end::End Navbar Links-->
    </div> <!--end::Container-->
</nav> <!--end::Header-->

app-vac-bootcamp24-ecom/src/templates/base/left-side-menu.html
{% load static %}
<!--begin::Sidebar-->
<aside class="app-sidebar bg-body-secondary shadow" data-bs-theme="dark"> <!--begin::Sidebar Brand-->
    <div class="sidebar-brand"> <!--begin::Brand Link--> <a href="" class="brand-link"> <!--begin::Brand Image--> <img src="{% static 'assets/img/AdminLTELogo.png' %}" alt="Logo app vac" class="brand-image opacity-75 shadow"> <!--end::Brand Image--> <!--begin::Brand Text--> <span class="brand-text fw-light">App Vac</span> <!--end::Brand Text--> </a> <!--end::Brand Link--> </div> <!--end::Sidebar Brand--> <!--begin::Sidebar Wrapper-->
    <div class="sidebar-wrapper">

        <nav class="mt-2"> <!--begin::Sidebar Menu-->
            <ul class="nav sidebar-menu flex-column" data-lte-toggle="treeview" role="menu" data-accordion="false">

                <li class="nav-item"> <a href="{% url 'usuarios:lista' %}" class="nav-link"> <i class="bi bi-person-badge"></i>
                        <p>Lista de Usuarios</p>
                    </a>
                </li>

                <li class="nav-item"> <a href="{% url 'pacientes:lista' %}" class="nav-link"> <i class="bi bi-person-heart"></i>
                        <p>Lista de Pacientes</p>
                    </a>
                </li>

                <li class="nav-item"> <a href="{% url 'vacunas:lista' %}" class="nav-link"> <i class="bi bi-bag-plus"></i>
                        <p>Lista de Vacunas</p>
                    </a>
                </li>
                <li class="nav-header">{AGRUPADOR}</li>
                <li class="nav-item"> <a href="#" class="nav-link"> <i class="nav-icon bi bi-box-arrow-in-right"></i>
                        <p>
                            {ITEM 2}
                            <i class="nav-arrow bi bi-chevron-right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item"> <a href="#" class="nav-link"> <i class="nav-icon bi bi-box-arrow-in-right"></i>
                                <p>
                                    {SUBITEM 1}
                                    <i class="nav-arrow bi bi-chevron-right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item"> <a href="" class="nav-link"> <i class="nav-icon bi bi-circle"></i>
                                        <p>{SUB SUBITEM 1}</p>
                                    </a> </li>
                                <li class="nav-item"> <a href="" class="nav-link"> <i class="nav-icon bi bi-circle"></i>
                                        <p>{SUB SUBITEM 2}</p>
                                    </a> </li>
                            </ul>
                        </li>
                        <li class="nav-item"> <a href="#" class="nav-link"> <i class="nav-icon bi bi-box-arrow-in-right"></i>
                                <p>
                                    {SUBITEM 2}
                                    <i class="nav-arrow bi bi-chevron-right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item"> <a href="" class="nav-link"> <i class="nav-icon bi bi-circle"></i>
                                        <p>{SUB SUBITEM 1}</p>
                                    </a> </li>
                                <li class="nav-item"> <a href="" class="nav-link"> <i class="nav-icon bi bi-circle"></i>
                                        <p>{SUB SUBITEM 2}</p>
                                    </a> </li>
                            </ul>
                        </li>
                        <li class="nav-item"> <a href="" class="nav-link"> <i class="nav-icon bi bi-circle"></i>
                                <p>{SUBITEM 3}</p>
                            </a> </li>
                    </ul>
                </li>

            </ul> <!--end::Sidebar Menu-->
        </nav>
    </div> <!--end::Sidebar Wrapper-->
</aside> <!--end::Sidebar-->