app-vac-bootcamp24-ecom/src/apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = "usuarios"

urlpatterns = [
    path('lista/', views.lista_usuarios, name="lista"),
    path('nuevo/', views.nuevo, name="nuevo"),
]

app-vac-bootcamp24-ecom/src/config/urls.py
from django.contrib import admin
from django.contrib.auth import views as views_django
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('inicio/', views.mi_pagina_inicio, name="inicio"),
    path('', views.mi_pagina_inicio, name="inicio"),

    path('base', views.BaseTemplateView.as_view(), name='base'),

    # path('login/', views.login, name="login"),
    # path('login/', views_django.LoginView.as_view(), name="login"),
    path('login/', views_django.LoginView.as_view(template_name="login_new.html"), name="login"),
    path('logout/', views_django.logout_then_login, name="logout"),
    
    # path('usuarios/lista/', views.lista_usuarios, name="lista_de_usuarios"),
    path('usuarios/', include("apps.usuarios.urls")),
    path('pacientes/', include("apps.pacientes.urls")),
    path('vacunas/', include("apps.vacunas.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app-vac-bootcamp24-ecom/src/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    dni = models.IntegerField(null=True)

    def __str__(self):
        return f"{self.id} - {self.username}. {self.first_name} - {self.last_name}"

app-vac-bootcamp24-ecom/src/apps/usuarios/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm


from .models import Usuario

class FormUsuario(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ["password", "username", "first_name", "last_name", "email", "is_active", "dni"]

class FormUser(UserCreationForm):
    # atributo1 = forms.CharField()
    username = forms.CharField(label="Nombre de usuario", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese un nombre de usuario'}))
    class Meta:
        model = Usuario
        fields = ["username", "first_name", "last_name", "email", "is_active", "dni"]
    
    def __init__(self, *args, **kwargs):
        super(FormUser, self).__init__(*args, **kwargs)

        add_class_form_control = ["first_name", "username", "last_name", "email", "dni", "password1", "password2"]
        
        for attr_field in add_class_form_control:
            self.fields[attr_field].widget.attrs["class"] = "form-control"
        

    def clean_dni(self):
        dni = self.cleaned_data["dni"]
        if not ( 7 <= len(str(dni)) <=8 ):
            raise ValidationError("el dni debe tener entre 7 y 8 digitos numericos")
        print(dni.__class__.__name__)
        return dni

app-vac-bootcamp24-ecom/src/apps/usuarios/views.py
from django.shortcuts import render, redirect

from .forms import FormUsuario, FormUser
from .models import Usuario


def nuevo(request):
    template_name = 'usuarios/nuevo_new.html'
    # form = FormUsuario()
    form = FormUser()
    message = ""
    if request.method == 'POST':
        form = FormUser(request.POST)
        if form.is_valid():
            form.save()
            return redirect("usuarios:lista")
        else:
            message = "No se pudo guardar de forma correcta el formulario"

    ctx = {
        "formUsuario": form,
        "message": message
    }
    return render(request, template_name, ctx)


def lista_usuarios(request):
    usuarios = Usuario.objects.all()  # filter(id__in=[1,2,3])#
    """
    u = Usuario.objects.filter(id=1).first()
    # u = Usuario.objects.get(id=5)
    print("TODOS LOS USUARIOS")
    if u is None:
        print("no existe")
    else:

        print(u)
        # print(u.query)
        #u = u[0]
        print(u.username)
    
    print("long:", len(usuarios))
    print("long:", usuarios.count())
    for us in usuarios:
        print(us.last_login)
    """
    ctx = {
        "usuarios": usuarios,
        "titulo": "LISTA DE USUARIOS"
    }
    return render(request, 'usuarios/lista_new.html', ctx)

app-vac-bootcamp24-ecom/src/templates/usuarios/lista.html
{% extends 'base/base.html' %}



{% block contenido %}
    <h1>Bienvenido, {{usuario_autenticado}}</h1>

    <h1>LISTA DE USUARIOS</h1>

    <a href="{% url 'usuarios:nuevo' %}">Nuevo usuario</a>

    <table>
        <tr>
            <th>Nombre de usuario</th>
            <th>Nombre</th>
            <th>Apellido</th>
        </tr>

        
        {% for us in usuarios %}
            <tr>
                <td>{{us.username}}</td>
                <td>
                    
                    {% if us.first_name %}
                        {{us.first_name}}
                    {% else %}
                        -
                    {% endif %}
                        
                    
                </td>
                <td>{{us.last_name|default:"-"}}</td>
        
            </tr>
            
        {% endfor %}
    </table>

{% endblock contenido %}

app-vac-bootcamp24-ecom/src/templates/usuarios/nuevo.html
{% extends 'base/base.html' %}



{% block contenido %}
    <h1>Nuevo usuario</h1>

    <form method="POST">{% csrf_token %}
     
        <!--
        <p>
            {{form.atributo1.label}}
            {{form.atributo1}}
        </p>
        -->
        {% include 'includes/forms_errors.html' with form=formUsuario %}
        
        {% comment %}
        <!--
        <div class="row">
            <div class="col">
                {{formUsuario.first_name.label}}
                {{formUsuario.first_name}}
            </div>
            <div class="col">
                {{formUsuario.last_name.label}}
                {{formUsuario.last_name}}
            </div>
        </div>
        -->
        {% endcomment %}

        {% include 'includes/forms.html' with form=formUsuario %}

        <hr>

        <button type="submit">Guardar</button>
        <a href="{% url 'usuarios:lista' %}">volver</a>
    </form>
{% endblock contenido %}